### ISSUE TITLE
GLOPs有没有统计过？多谢

### ISSUE THREAD

**Issue by lixiangMindSpore** [prakharg24/yoloret#5]

**Comment by prakharg24** [comment]
Hi @lixiangMindSpore 

We discuss in detail in our paper (https://arxiv.org/abs/2110.13713) why we prefer to not use indirect metrics of comparison like model size or FLOPs, since each device can have different requirements and only on-device latency are a good practical comparisons. For example, when working with GPUs (in our case edge GPUs), the ease of parallelization, or in other words 'network fragmentation', is far more important than the model size or FLOPs.

Despite all this, if you really want to extract the FLOP values, it should be pretty straightforward since we are using tensorflow. You can use the internal tensorflow profiling tools for calculating FLOPs and other metrics.

Hope this helps.

**Comment by lixiangMindSpore** [comment]
> Hi @lixiangMindSpore
> 
> We discuss in detail in our paper (https://arxiv.org/abs/2110.13713) why we prefer to not use indirect metrics of comparison like model size or FLOPs, since each device can have different requirements and only on-device latency are a good practical comparisons. For example, when working with GPUs (in our case edge GPUs), the ease of parallelization, or in other words 'network fragmentation', is far more important than the model size or FLOPs.
> 
> Despite all this, if you really want to extract the FLOP values, it should be pretty straightforward since we are using tensorflow. You can use the internal tensorflow profiling tools for calculating FLOPs and other metrics.
> 
> Hope this helps.

Thanks, but I need to use it in edge device urgently. Accordingly, I need GFLOPs, can you tell me the rough value of GFLOPs of YOLO-ReT-M0.75 (416*416)？Thank you so much!
